name: terraform-automation
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: terraform1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::109443434700:role/s3-role-federation
          role-session-name: Github
          aws-region: ${{ env.AWS_REGION }}

      - name: s3
        run: |
          aws s3 ls